### ISSUE TITLE
build stopped

### ISSUE THREAD

**Issue by MoNTE48** [CyanogenMod/android_external_gello_build#1]
Note: Some input files additionally use or override a deprecated API.
Note: ../swe/browser/src/com/android/browser/reflect/ReflectHelper.java uses unchecked or unsafe operations.
100 warnings
[13536/13539] ACTION Linting swe_android_browser_apk

com/android/browser/AddBookmarkPage.class Implicitly using the default locale is a common source of bugs: Use `toLowerCase(Locale)` instead: DefaultLocale [warning]
com/android/browser/mynavigation/AddMyNavigationPage.class Implicitly using the default locale is a common source of bugs: Use `toLowerCase(Locale)` instead: DefaultLocale [warning]
com/android/browser/FetchUrlMimeType.class Implicitly using the default locale is a common source of bugs: Use `toLowerCase(Locale)` instead: DefaultLocale [warning]
com/android/browser/NetworkStateHandler$1.class Implicitly using the default locale is a common source of bugs: Use `toLowerCase(Locale)` instead: DefaultLocale [warning]
com/android/browser/NetworkStateHandler$1.class Implicitly using the default locale is a common source of bugs: Use `toLowerCase(Locale)` instead: DefaultLocale [warning]
com/android/browser/UrlUtils.class Implicitly using the default locale is a common source of bugs: Use `toLowerCase(Locale)` instead: DefaultLocale [warning]
com/android/browser/UrlUtils.class Implicitly using the default locale is a common source of bugs: Use `toLowerCase(Locale)` instead: DefaultLocale [warning]
com/android/browser/platformsupport/WebAddress.class Implicitly using the default locale is a common source of bugs: Use `toLowerCase(Locale)` instead: DefaultLocale [warning]
../../../../../../tmp/tmpHNrrTo/0/BookmarkExpandableView.java:290 Use `new SparseArray<BreadCrumbView>(...)` instead for better performance: UseSparseArrays [warning]
                new HashMap<Integer, BreadCrumbView>();
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../../../../tmp/tmpHNrrTo/0/BrowserBookmarksPage.java:110 Use `new SparseArray<BrowserBookmarksAdapter>(...)` instead for better performance: UseSparseArrays [warning]
    HashMap<Integer, BrowserBookmarksAdapter> mBookmarkAdapters = new HashMap<Integer, BrowserBookmarksAdapter>();
                                                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../../../../tmp/tmpHNrrTo/0/MyNavigationTemplate.java:53 Use `new SparseArray<MyNavigationTemplate>(...)` instead for better performance: UseSparseArrays [warning]
            new HashMap<Integer, MyNavigationTemplate>();
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../../../../tmp/tmpHNrrTo/0/Template.java:37 Use `new SparseArray<Template>(...)` instead for better performance: UseSparseArrays [warning]
    private static HashMap<Integer, Template> sCachedTemplates = new HashMap<Integer, Template>();
                                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
com/android/browser/appmenu/AppMenuButtonHelper.class `com/android/browser/appmenu/AppMenuButtonHelper#onTouch` should call `View#performClick` when a click is detected: ClickableViewAccessibility [warning]
../../../../../../tmp/tmpHNrrTo/0/Controller.java:2650 Use "`Gravity.END`" instead of "`Gravity.RIGHT`" to ensure correct behavior in right-to-left locales: RtlHardcoded [warning]
        i.putExtra("gravity", Gravity.RIGHT | Gravity.TOP);
                                      ~~~~~

Lint found 14 new issues.
 - For full explanation refer to out/Release/swe_android_browser_apk/lint_result.xml
 - Wanna suppress these issues?
    1. Read comment in build/android/lint/suppressions.xml
    2. Run "python build/android/lint/suppress.py out/Release/swe_android_browser_apk/lint_result.xml"

[13537/13539] ACTION Packaging swe_android_browser_apk
FAILED: cd ../../chrome; python ../build/android/gyp/ant.py -- -quiet "-DDEX_FILE_PATH=../out/Release/swe_android_browser_apk/classes.dex" "-DANDROID_SDK_ROOT=/home/monte48/work/android_external_gello_build/env/src/third_party/android_tools/sdk/" "-DANDROID_SDK_TOOLS=/home/monte48/work/android_external_gello_build/env/src/third_party/android_tools/sdk//build-tools/23.0.0" "-DRESOURCE_PACKAGED_APK_NAME=SWE_AndroidBrowser-resources.ap_" "-DAPK_NAME=SWE_AndroidBrowser" "-DCONFIGURATION_NAME=Release" "-DNATIVE_LIBS_DIR=../out/Release/swe_android_browser_apk/libs" "-DOUT_DIR=../out/Release/swe_android_browser_apk" "-DUNSIGNED_APK_PATH=../out/Release/swe_android_browser_apk/SWE_AndroidBrowser-unsigned.apk" "-DEMMA_INSTRUMENT=0" "-DEMMA_DEVICE_JAR=/home/monte48/work/android_external_gello_build/env/src/third_party/android_tools/sdk//tools/lib/emma_device.jar" "-Dbasedir=." -buildfile ../build/android/ant/apk-package.xml
Traceback (most recent call last):
  File "../build/android/gyp/ant.py", line 65, in <module>
    sys.exit(main(sys.argv))
  File "../build/android/gyp/ant.py", line 31, in main
    stdout = build_utils.CheckOutput(['ant'] + args)
  File "/home/monte48/work/android_external_gello_build/env/src/build/android/gyp/util/build_utils.py", line 148, in CheckOutput
    stdout=subprocess.PIPE, stderr=subprocess.PIPE, cwd=cwd)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied
ninja: build stopped: subcommand failed.

**Comment by MoNTE48** [comment]
Pls, add in readme
sudo apt-get install ninja
And what this :
./gello_build.sh: line 50: gclient: command not found

**Comment by Alphakilo** [comment]
@MoNTE48 
run `./gello_build.sh --depot` first.
